
server:
  port: 8080

spring:
  datasource:
    name: dev
    url: jdbc:mysql://localhost:3306/marker?serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis:
  mapper-locations: "com/poldichen/markerspringboot/dao/mapper/*.xml"

jwt:
  prefix: marker
  secret: 123456